
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project
name: NET 7.0 CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
  
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    env:
      Solution_Path: dotnet7_wpf_app.sln
      Actions_Allow_Unsecure_Commands: true
      INNO_VERSION: 6.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Nerdbank.GitVersioning to set version variables
        uses: aarnott/nbgv@v0.4.0
        with:
          setAllVars: true

      # - name: Install .NET Core
      #   uses: actions/setup-dotnet@v2
      #   with:
      #     dotnet-version: ${{ matrix.dotnet-version }}

      # - name: Restore Packages
      #   run: dotnet restore ${{ env.Solution_Path }}
      #   working-directory: ${{ github.workspace }}

      # - name: Build
      #   run: dotnet build --configuration Release --no-restore ${{ env.Solution_Path }}
      #   working-directory: ${{ github.workspace }}

      - name: print version number
        run: echo $env:NBGV_Version
        
      - name: Download Inno Setup installer
        run: curl -L -o installer.exe http://files.jrsoftware.org/is/6/innosetup-${{ env.INNO_VERSION }}.exe

      - name: Install Inno Setup
        run: Start-Process ./installer.exe -NoNewWindow -Wait -ArgumentList "/verysilent /allusers"

      - name: Build Installer
        run: "%programfiles(x86)%\Inno Setup 6\iscc.exe" /dMyAppVersion="1.0.0.0" "scripts\InnoSetupScript.iss"
        shell: cmd

